### ISSUE TITLE
Wont start

### ISSUE THREAD

**Issue by rcocchiararo** [monitoringartist/control-center-zenoss-searcher#1]
Hi

I just saw in the zenoss wiki that there were additional templates for adding stuff to zenoss, and i tried testing this one:

W1109 16:09:33.856957 00001 controller.go:844] Health check "health" failed.

It wont start.

**Comment by jangaraj** [comment]
It's known issue: health checks are failing, but app is up and running. I've spent 2 days by digging and debugging and still I don't know why. Health script returns 0, which means OK.

**Comment by rcocchiararo** [comment]
Oh, it would not get into the app here, maybe i did not give the DNS enough
time after creating the new virtual host?

**Comment by jangaraj** [comment]
And what is error? How does it look in your browser? Keep in mind, that, health check is not relevant in this case.

**Comment by rcocchiararo** [comment]
Page not found or something like that (not in place right now).

I thought it was because of the health check indicating that it was not
working.

**Comment by jangaraj** [comment]
Page not found -> probably DNS problem.

**Comment by rcocchiararo** [comment]
Indeed, i came back and it was working, i was to eager it seems :P

**Comment by jangaraj** [comment]
README updated: https://github.com/monitoringartist/control-center-zenoss-searcher/blob/master/README.md#troubleshooting
